apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
  namespace: ceu
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
#  fileSystemId: fs-0164f366e3ff8e5ac
  fileSystemId: fs-0547919cb4917eee7
  directoryPerms: "777"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
#  basePath: "/contents"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: ceu
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: efs-sc

